/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as import0 from '@angular/core';
import * as import1 from './app.module';
class FabricModuleInjector extends import0.ɵNgModuleInjector<import1.FabricModule> {
  _FabricModule_0:import1.FabricModule;
  constructor(parent:import0.Injector) {
    super(parent,([] as any[]),([] as any[]));
  }
  createInternal():import1.FabricModule {
    this._FabricModule_0 = new import1.FabricModule();
    return this._FabricModule_0;
  }
  getInternal(token:any,notFoundResult:any):any {
    if ((token === import1.FabricModule)) { return this._FabricModule_0; }
    return notFoundResult;
  }
  destroyInternal():void {
  }
}
export const FabricModuleNgFactory:import0.NgModuleFactory<import1.FabricModule> = new import0.NgModuleFactory<any>(FabricModuleInjector,import1.FabricModule);
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL1VzZXJzL21yZWluaGFyZHQvRG9jdW1lbnRzL1Byb2dyYW1taWVydW5nL3JlcG9zaXRvcmllcy9naXQvcHJpdmF0ZS9uYXRpdmVzY3JpcHQvbmF0aXZlc2NyaXB0LWZhYnJpYy9zcmMvYXBwL2FwcC5tb2R1bGUubmdmYWN0b3J5LnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vVXNlcnMvbXJlaW5oYXJkdC9Eb2N1bWVudHMvUHJvZ3JhbW1pZXJ1bmcvcmVwb3NpdG9yaWVzL2dpdC9wcml2YXRlL25hdGl2ZXNjcmlwdC9uYXRpdmVzY3JpcHQtZmFicmljL3NyYy9hcHAvYXBwLm1vZHVsZS50cyJdLCJzb3VyY2VzQ29udGVudCI6WyIgIl0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7In0=
